export const FETCH_EDITORS_CHOICE='FETCH_EDITORS_CHOICE';
export const FETCH_EDITORS_CHOICE_SUCCESS='FETCH_EDITORS_CHOICE_SUCCESS';
export const FETCH_EDITORS_CHOICE_FAIL='FETCH_EDITORS_CHOICE_FAIL';
export const FETCH_JUST_IN='FETCH_JUST_IN';
export const FETCH_JUST_IN_SUCCESS='FETCH_JUST_IN_SUCCESS';
export const FETCH_JUST_IN_FAIL='FETCH_JUST_IN_FAIL';
