export const FETCH_EDITORS_CHOICE='FETCH_EDITORS_CHOICE';
export const FETCH_EDITORS_CHOICE_SUCCESS='FETCH_EDITORS_CHOICE_SUCCESS';
export const FETCH_EDITORS_CHOICE_FAIL='FETCH_EDITORS_CHOICE_FAIL';
